# GitHub recognizes this file and renders the "Sponsor" button on the repo + profile.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [314159DD]
buy_me_a_coffee: 314159DD
